import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./editor.css";
import Providers from "./providers";
import Navbar from "@/components/Navbar";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from "@/components/ui/sonner"
import CreateWorkspaceModal from "@/components/CreateWorkspaceModal";
import CreateChannelModal from "@/components/CreateChannelModal";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" suppressHydrationWarning >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NextTopLoader showSpinner={false} color="#2a07f0" />
          <Providers>
            <CreateWorkspaceModal />
            <CreateChannelModal />
            {/* <Navbar /> */}
            {children}
            <Toaster />
          </Providers>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
